### PR TITLE
CMake build

### PR DESCRIPTION
**Pull request by gokhanettin**
This PR deletes `pardus-store.pro` file and adds CmakeLists.txt file to build the project with CMake. Note that QtCreator along with many other IDEs automatically recognizes CMakeLists.txt. For QtCreator go to `File > Open File or Project...` and select the CMakeLists.txt at the top level project directory. Files and directories used for Debian packaging are also modified accordingly.

Additionally, it also describes the project as well as how to build and run it on README.md. We had better also have a packaging guide on README, so I left it as a `TODO`. Another `TODO` could be a continuous build and testing.

### CODE REVIEW

**Comment by yunusem** [comment]
Why can't we keep both CMakelist and pro file.

**Comment by gokhanettin** [comment]
It seems debian tools selects CMake for packaging when they both exist. It is also inconvenient to maintain two build systems. When you add a new source file you have to include it in both .pro and CMakeLists.txt.

**Comment by yunusem** [comment]
Well,  does IDE (QtCreator) supports auto editing when source class (cpp &h) added or discarted ? Btw. I think you can use pro file to create Cmakefile though.

**Comment by gokhanettin** [comment]
No, it won't automatically add or delete files from CMakeLists.txt when you do so from graphical interface of QtCreator. It is the only downside I could think of. But CMake is supported by many different IDE's and editors. CMake creates a compilation database known as `compile_commands.json` which is used for autocompletion by those IDEs and editors.

CMake might seem to be an overkill for a project at this size, but when a project grows and requires more configuration such as generating headers/sources from template files, CMake is the way to go.

**Comment by gokhanettin** [comment]
We can come back to talk about CMake when we really need it. For now, we can continue with qmake.

**Pull request closed without merging**
